[theme]
background = "black"
primary = "cyan"
secondary = "light black"
title = "light cyan"
playing = "light white"
playing_bg = "black"
highlight = "light cyan"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "light cyan"
statusbar_bg = "cyan"
cmdline = "light white"
cmdline_bg = "black"
